[modules]
left = ["Workspaces", "SystemInfo"]
center = ["WindowTitle"]
right = [["MediaPlayer", "Clock"], ["Tray", "Privacy", "Settings"]]

[workspaces]
workspace_names = [
    "1  ",
    "2  ",
    "3  ",
    "4  ",
    "5  ",
    "6  ",
    "7  ",
    "8  ",
    "9 󱥸 ",
]

[system_info]
indicators = ["Cpu", "Memory", "DownloadSpeed", "UploadSpeed"]

[clock]
format = "%H:%M:%S"

[media_player]
max_title_length = 30

[settings]
battery_format = "IconAndPercentage"
indicators = ["Network", "Bluetooth", "Audio", "Battery"]
